import styles from "@/styles/Home.module.scss";
import Head from "next/head";
import Hero from "@/components/Hero";
import Loader from "@/components/Layout/Transition";
import FoldText from "@/components/Accents/FoldText";
export default function Home() {
  return (
    <>
      <Head>
        <title>Alx Li | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Loader>
        <main className={styles.main}>
          <Hero text={"catchphrase//"} logo />
          <FoldText />
          <div style={{ height: "100vh" }} />
        </main>
      </Loader>
    </>
  );
}
