import styles from "@/styles/Home.module.scss";
import Head from "next/head";
import Hero from "@/components/Home/Hero";
import Layout from "@/components/Layout/Transition";
import TextScrollv2 from "@/components/Common/TextScrollv2";
import FoldText from "@/components/Accents/FoldText";
export default function Contact() {
  return (
    <>
      <Head>
        <title>Alx Li | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Layout>
        <main className={styles.main}>
          <Hero text={"work.in.progress//"} />
          <FoldText />
        </main>
      </Layout>
    </>
  );
}
